### PR TITLE
Work around issue with persistent dirs with `UnprivilegedUserNamespacesExecutor`

### LINKED ISSUE #77: Internet access tests failing for `UnprivilegedUserNamespacesExecutor` when using Linux >= 5.11
```
     Testing Running tests...
┌ Info: On a UserNSSandbox_jll-capable platform
└   sandbox_path = "/home/mose/.julia/artifacts/cc902648a99eecab464d4a99eca4104931591e63/bin/sandbox"
Test Summary: | Pass  Total
SandboxConfig |   27     27
Test Summary:                      | Pass  Total
UnprivilegedUserNamespacesExecutor |    2      2
0+1 records in
0+1 records out
dd: error writing 'sample.txt': No space left on device
0+1 records in
0+0 records out
Test Summary:             | Pass  Total
Customize the tempfs size |    2      2
┌ Error: Skipping Docker tests, as it does not seem to be available
└ @ Main ~/.julia/dev/Sandbox/test/Docker.jl:83
Hit:1 https://deb.debian.org/debian buster InRelease
Get:2 https://deb.debian.org/debian buster/main Translation-en [5968 kB]
Fetched 5968 kB in 3s (2266 kB/s)          
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
W: No sandbox user '_apt' on the system, can not drop privileges
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  krb5-locales libcurl4 libgssapi-krb5-2 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common libnghttp2-14 libpsl5 librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db
  libssh2-1 publicsuffix
Suggested packages:
  krb5-doc krb5-user libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql
The following NEW packages will be installed:
  curl krb5-locales libcurl4 libgssapi-krb5-2 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common libnghttp2-14 libpsl5 librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db
  libssh2-1 publicsuffix
0 upgraded, 18 newly installed, 0 to remove and 0 not upgraded.
Need to get 2473 kB of archives.
After this operation, 5841 kB of additional disk space will be used.
Get:1 https://deb.debian.org/debian buster/main amd64 krb5-locales all 1.17-3+deb10u3 [95.5 kB]
Get:2 https://deb.debian.org/debian buster/main amd64 libkeyutils1 amd64 1.6-6 [15.0 kB]
Get:3 https://deb.debian.org/debian buster/main amd64 libkrb5support0 amd64 1.17-3+deb10u3 [65.8 kB]
Get:4 https://deb.debian.org/debian buster/main amd64 libk5crypto3 amd64 1.17-3+deb10u3 [122 kB]
Get:5 https://deb.debian.org/debian buster/main amd64 libkrb5-3 amd64 1.17-3+deb10u3 [370 kB]
Get:6 https://deb.debian.org/debian buster/main amd64 libgssapi-krb5-2 amd64 1.17-3+deb10u3 [158 kB]
Get:7 https://deb.debian.org/debian buster/main amd64 libsasl2-modules-db amd64 2.1.27+dfsg-1+deb10u1 [69.1 kB]
Get:8 https://deb.debian.org/debian buster/main amd64 libsasl2-2 amd64 2.1.27+dfsg-1+deb10u1 [106 kB]
Get:9 https://deb.debian.org/debian buster/main amd64 libldap-common all 2.4.47+dfsg-3+deb10u6 [90.0 kB]
Get:10 https://deb.debian.org/debian buster/main amd64 libldap-2.4-2 amd64 2.4.47+dfsg-3+deb10u6 [224 kB]
Get:11 https://deb.debian.org/debian buster/main amd64 libnghttp2-14 amd64 1.36.0-2+deb10u1 [85.0 kB]
Get:12 https://deb.debian.org/debian buster/main amd64 libpsl5 amd64 0.20.2-2 [53.7 kB]
Get:13 https://deb.debian.org/debian buster/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2 [60.5 kB]
Get:14 https://deb.debian.org/debian buster/main amd64 libssh2-1 amd64 1.8.0-2.1 [140 kB]
Get:15 https://deb.debian.org/debian buster/main amd64 libcurl4 amd64 7.64.0-4+deb10u2 [332 kB]
Get:16 https://deb.debian.org/debian buster/main amd64 curl amd64 7.64.0-4+deb10u2 [265 kB]
Get:17 https://deb.debian.org/debian buster/main amd64 libsasl2-modules amd64 2.1.27+dfsg-1+deb10u1 [104 kB]
Get:18 https://deb.debian.org/debian buster/main amd64 publicsuffix all 20190415.1030-1 [116 kB]
Fetched 2473 kB in 1s (3362 kB/s)  
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package krb5-locales.
(Reading database ... 6787 files and directories currently installed.)
Preparing to unpack .../00-krb5-locales_1.17-3+deb10u3_all.deb ...
Unpacking krb5-locales (1.17-3+deb10u3) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/00-krb5-locales_1.17-3+deb10u3_all.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libkeyutils1:amd64.
Preparing to unpack .../01-libkeyutils1_1.6-6_amd64.deb ...
Unpacking libkeyutils1:amd64 (1.6-6) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/01-libkeyutils1_1.6-6_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
Selecting previously unselected package libkrb5support0:amd64.
Preparing to unpack .../02-libkrb5support0_1.17-3+deb10u3_amd64.deb ...
Unpacking libkrb5support0:amd64 (1.17-3+deb10u3) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/02-libkrb5support0_1.17-3+deb10u3_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
Selecting previously unselected package libk5crypto3:amd64.
Preparing to unpack .../03-libk5crypto3_1.17-3+deb10u3_amd64.deb ...
Unpacking libk5crypto3:amd64 (1.17-3+deb10u3) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/03-libk5crypto3_1.17-3+deb10u3_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
Selecting previously unselected package libkrb5-3:amd64.
Preparing to unpack .../04-libkrb5-3_1.17-3+deb10u3_amd64.deb ...
Unpacking libkrb5-3:amd64 (1.17-3+deb10u3) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/04-libkrb5-3_1.17-3+deb10u3_amd64.deb (--unpack):
 unable to install new version of './usr/lib/x86_64-linux-gnu/krb5': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libgssapi-krb5-2:amd64.
Preparing to unpack .../05-libgssapi-krb5-2_1.17-3+deb10u3_amd64.deb ...
Unpacking libgssapi-krb5-2:amd64 (1.17-3+deb10u3) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/05-libgssapi-krb5-2_1.17-3+deb10u3_amd64.deb (--unpack):
 unable to install new version of './etc/gss': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libsasl2-modules-db:amd64.
Preparing to unpack .../06-libsasl2-modules-db_2.1.27+dfsg-1+deb10u1_amd64.deb ...
Unpacking libsasl2-modules-db:amd64 (2.1.27+dfsg-1+deb10u1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/06-libsasl2-modules-db_2.1.27+dfsg-1+deb10u1_amd64.deb (--unpack):
 unable to install new version of './usr/lib/x86_64-linux-gnu/sasl2': Invalid cross-device link
Selecting previously unselected package libsasl2-2:amd64.
Preparing to unpack .../07-libsasl2-2_2.1.27+dfsg-1+deb10u1_amd64.deb ...
Unpacking libsasl2-2:amd64 (2.1.27+dfsg-1+deb10u1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/07-libsasl2-2_2.1.27+dfsg-1+deb10u1_amd64.deb (--unpack):
 unable to install new version of './usr/lib/sasl2': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libldap-common.
Preparing to unpack .../08-libldap-common_2.4.47+dfsg-3+deb10u6_all.deb ...
Unpacking libldap-common (2.4.47+dfsg-3+deb10u6) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/08-libldap-common_2.4.47+dfsg-3+deb10u6_all.deb (--unpack):
 unable to install new version of './etc/ldap': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libldap-2.4-2:amd64.
Preparing to unpack .../09-libldap-2.4-2_2.4.47+dfsg-3+deb10u6_amd64.deb ...
Unpacking libldap-2.4-2:amd64 (2.4.47+dfsg-3+deb10u6) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/09-libldap-2.4-2_2.4.47+dfsg-3+deb10u6_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libnghttp2-14:amd64.
Preparing to unpack .../10-libnghttp2-14_1.36.0-2+deb10u1_amd64.deb ...
Unpacking libnghttp2-14:amd64 (1.36.0-2+deb10u1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/10-libnghttp2-14_1.36.0-2+deb10u1_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
Selecting previously unselected package libpsl5:amd64.
Preparing to unpack .../11-libpsl5_0.20.2-2_amd64.deb ...
Unpacking libpsl5:amd64 (0.20.2-2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/11-libpsl5_0.20.2-2_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
Selecting previously unselected package librtmp1:amd64.
Preparing to unpack .../12-librtmp1_2.4+20151223.gitfa8646d.1-2_amd64.deb ...
Unpacking librtmp1:amd64 (2.4+20151223.gitfa8646d.1-2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/12-librtmp1_2.4+20151223.gitfa8646d.1-2_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
Selecting previously unselected package libssh2-1:amd64.
Preparing to unpack .../13-libssh2-1_1.8.0-2.1_amd64.deb ...
Unpacking libssh2-1:amd64 (1.8.0-2.1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/13-libssh2-1_1.8.0-2.1_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
Selecting previously unselected package libcurl4:amd64.
Preparing to unpack .../14-libcurl4_7.64.0-4+deb10u2_amd64.deb ...
Unpacking libcurl4:amd64 (7.64.0-4+deb10u2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/14-libcurl4_7.64.0-4+deb10u2_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package curl.
Preparing to unpack .../15-curl_7.64.0-4+deb10u2_amd64.deb ...
Unpacking curl (7.64.0-4+deb10u2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/15-curl_7.64.0-4+deb10u2_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libsasl2-modules:amd64.
Preparing to unpack .../16-libsasl2-modules_2.1.27+dfsg-1+deb10u1_amd64.deb ...
Unpacking libsasl2-modules:amd64 (2.1.27+dfsg-1+deb10u1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/16-libsasl2-modules_2.1.27+dfsg-1+deb10u1_amd64.deb (--unpack):
 unable to install new version of './etc/logcheck': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package publicsuffix.
Preparing to unpack .../17-publicsuffix_20190415.1030-1_all.deb ...
Unpacking publicsuffix (20190415.1030-1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-p8agL7/17-publicsuffix_20190415.1030-1_all.deb (--unpack):
 unable to install new version of './usr/share/doc': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /tmp/apt-dpkg-install-p8agL7/00-krb5-locales_1.17-3+deb10u3_all.deb
 /tmp/apt-dpkg-install-p8agL7/01-libkeyutils1_1.6-6_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/02-libkrb5support0_1.17-3+deb10u3_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/03-libk5crypto3_1.17-3+deb10u3_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/04-libkrb5-3_1.17-3+deb10u3_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/05-libgssapi-krb5-2_1.17-3+deb10u3_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/06-libsasl2-modules-db_2.1.27+dfsg-1+deb10u1_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/07-libsasl2-2_2.1.27+dfsg-1+deb10u1_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/08-libldap-common_2.4.47+dfsg-3+deb10u6_all.deb
 /tmp/apt-dpkg-install-p8agL7/09-libldap-2.4-2_2.4.47+dfsg-3+deb10u6_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/10-libnghttp2-14_1.36.0-2+deb10u1_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/11-libpsl5_0.20.2-2_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/12-librtmp1_2.4+20151223.gitfa8646d.1-2_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/13-libssh2-1_1.8.0-2.1_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/14-libcurl4_7.64.0-4+deb10u2_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/15-curl_7.64.0-4+deb10u2_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/16-libsasl2-modules_2.1.27+dfsg-1+deb10u1_amd64.deb
 /tmp/apt-dpkg-install-p8agL7/17-publicsuffix_20190415.1030-1_all.deb
W: No sandbox user '_apt' on the system, can not drop privileges
W: chown to root:adm of file /var/log/apt/term.log failed - OpenLog (22: Invalid argument)
E: Sub-process /usr/bin/dpkg returned an error code (1)
Internet access: Test Failed at /home/mose/.julia/dev/Sandbox/test/Sandbox.jl:335
  Expression: success(exe, config, `/bin/sh -c "apt update && apt install -y curl && curl -L $(socrates_url) -o /tmp/rw_dir/$(basename(socrates_url))"`)
Stacktrace:
 [1] macro expansion
   @ /usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] (::var"#65#89"{String})(exe::UnprivilegedUserNamespacesExecutor)
   @ Main ~/.julia/dev/Sandbox/test/Sandbox.jl:335
Internet access: Test Failed at /home/mose/.julia/dev/Sandbox/test/Sandbox.jl:337
  Expression: isfile(socrates_path)
Stacktrace:
 [1] macro expansion
   @ /usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] (::var"#62#86"{DataType})(rw_dir::String)
   @ Main ~/.julia/dev/Sandbox/test/Sandbox.jl:337
Internet access: Error During Test at /home/mose/.julia/dev/Sandbox/test/Sandbox.jl:338
  Test threw exception
  Expression: open((io->begin
                bytes2hex(sha256(io))
            end), socrates_path) == socrates_hash
  SystemError: opening file "/tmp/jl_im3pq3/socrates.tar.xz": No such file or directory
  Stacktrace:
   [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
     @ Base ./error.jl:174
   [2] #systemerror#68
     @ ./error.jl:173 [inlined]
   [3] systemerror
     @ ./error.jl:173 [inlined]
   [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
     @ Base ./iostream.jl:293
   [5] open
     @ ./iostream.jl:282 [inlined]
   [6] open(f::var"#66#90", args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
     @ Base ./io.jl:328
   [7] open
     @ ./io.jl:328 [inlined]
   [8] macro expansion
     @ /usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
   [9] (::var"#62#86"{DataType})(rw_dir::String)
     @ Main ~/.julia/dev/Sandbox/test/Sandbox.jl:338
Test Summary:                                 | Pass  Fail  Error  Total
UnprivilegedUserNamespacesExecutor Sandboxing |   63     2      1     66
  capturing stdout/stderr                     |    3                   3
  ignorestatus()                              |    2                   2
  environment passing                         |    4                   4
  reading from maps                           |    2                   2
  writing to workspaces                       |    3                   3
  pipelining                                  |    3                   3
  read-only mounts are really read-only       |   14                  14
  entrypoint                                  |    6                   6
  persistence                                 |    9                   9
  explicit user and group                     |   12                  12
  hostname                                    |    2                   2
  Internet access                             |    3     2      1      6
ERROR: LoadError: Some tests did not pass: 63 passed, 2 failed, 1 errored, 0 broken.
in expression starting at /home/mose/.julia/dev/Sandbox/test/Sandbox.jl:21
in expression starting at /home/mose/.julia/dev/Sandbox/test/runtests.jl:39
ERROR: Package Sandbox errored during testing
```

### PR DESCRIPTION
**Pull request by giordano**
This is still quite not working for me, but opening for feedback.

This will eventually fix #77.

### CODE REVIEW

**Comment by giordano** [comment]
So, with the changes in this PR, this example
```julia
using Sandbox, Scratch, UserNSSandbox_jll
@show UserNSSandbox_jll.sandbox_path
mktempdir() do rw_dir
    config = SandboxConfig(
        Dict("/" => Sandbox.debian_rootfs()),
        Dict("/tmp/rw_dir" => rw_dir),
        Dict("HOME" => "/root");
        persist=true,
    )
    with_executor(UnprivilegedUserNamespacesExecutor) do exe
        exe.persistence_dir = @get_scratch!("tmpfs_xattr_workaround")
        success(exe, config, `/bin/sh -c "apt update && apt install -y curl"`)
    end
end
```
works for me, but the tests still fail with the same error as in #77, which very much confuses me.  (Yes, I did set `ENV["SANDBOX_BUILD_LOCAL_SANDBOX"] = "true"` and the path of the runner printed during the tests is the one from the scratchspace.)

File: deps/userns_sandbox.c [hunk 1]
```diff
@@ -263,7 +263,7 @@ static void mount_overlay(const char * src, const char * dest, const char * bnam
   mkpath(work);
 
   // Construct the opts, mount the overlay
-  snprintf(opts, sizeof(opts), "lowerdir=%s,upperdir=%s,workdir=%s", src, upper, work);
+  snprintf(opts, sizeof(opts), "userxattr,lowerdir=%s,upperdir=%s,workdir=%s", src, upper, work);
```
Comment (giordano) [inline deps/userns_sandbox.c:266]: I'm not quite sure this should be always set.  What would be the a good way forward?  Passing yet another option from the command line for whether to use it?

File: test/Sandbox.jl [hunk 2]
```diff
@@ -307,15 +307,20 @@ for executor in all_executors
...
-                    Dict("/tmp/rw_dir" => rw_dir),
+                    Dict("/tmp/rw_dir" => rw_dir);
+                    persist,
                 )
 
                 # Test that we can use `wget` (née busybox) within the alpine rootfs to download something
                 socrates_url = "https://github.com/staticfloat/small_bin/raw/master/socrates.tar.xz"
                 socrates_hash = "61bcf109fcb749ee7b6a570a6057602c08c836b6f81091eab7aa5f5870ec6475"
                 with_executor(executor) do exe
+                    persist && (exe.persistence_dir = @get_scratch!("tmpfs_xattr_workaround"))
```
Comment (giordano) [inline test/Sandbox.jl:323]: I've put this year, but probably should go to https://github.com/staticfloat/Sandbox.jl/blob/f484672e5b5f3aff2e30b56821c18fd3d3e5d581/src/UserNamespaces.jl#L169 instead?

**Comment by giordano** [comment]
Fun, now the tests with local build of the userns sandbox are failing with `Invalid cross-device link` errors

image

File: src/UserNamespaces.jl [hunk 3]
```diff
@@ -162,11 +162,15 @@ function build_executor_command(exe::UserNamespacesExecutor, config::SandboxConf
         append!(cmd_string, ["--entrypoint", config.entrypoint])
     end
 
+    needs_userxattr = exe isa UnprivilegedUserNamespacesExecutor && !Sandbox.probe_xattr("user")
```
Comment (staticfloat) [inline src/UserNamespaces.jl:165]: I'm waffling on whether this is the best way to test this.  I'm thinking it might be better to just add some C code to create a little probe that does things inside of sandboxes.

**Comment by staticfloat** [comment]
Our efforts to solve this have been stymied by a number of confounding factors, but I think I may have finally wrangled it.  The issues include:

* On newer kernels, you need to set `userxattr` on overlay mounts, otherwise you get failures to `mv` directories (manifesting as `invalid cross-device link` within the sandbox, and `failed to set xattr on upper` in the kernel log). See https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html#renaming-directories for a bit more detail.

* We cannot use `zfs` as the backing filesystem for an overlay's upper directory.  Trying to do this will manifest in `mount()` failing within the sandbox, and the kernel log complaining about a lack of the `RENAME_WHITEOUT` feature.

* Ubuntu patches spoil lazy devs like me.

* Many of these filesystem rules work one way in the host environment, and a different way when inside of the sandbox, which means that nested sandboxing is often the most difficult challenge.

I've made some changes here to default to `persist = true`.  Not only is it a cool and useful feature with very little overhead, it makes it a lot easier on `userxattr` systems.  We have a fancy new search algorithm for a directory that is able to be mounted against, which should aid us in nested sandboxing.

@giordano can you check locally that this works for you?  I'm passing tests on a 6.1 Arch kernel in an EC2 instance, but you're my most important Arch customer.  :)

Because we're changing the `persist` default here, I think this is worth bumping version numbers over.  There's also a significant amount of code here, so I may want to take a second pass in a few days to try and re-organize things a bit.
